[tools]
bun = "latest"
node = "latest"
pnpm = "latest"
uv = "latest"
go = "latest"
java = "latest"
deno = "latest"
bats = "latest"

"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:yaml-language-server" = "latest"

"npm:@earendil-works/pi-coding-agent" = "latest"
"cargo:shpool" = "latest"
rust = "latest"

"cargo:worktrunk" = "latest"

[settings]
npm.bun = true
idiomatic_version_file_enable_tools = ["python"]
lockfile = true

[env]
PKG_CONFIG_PATH = "{{env.HOME}}/.nix-profile/lib/pkgconfig"
LD_LIBRARY_PATH = "{{env.HOME}}/.nix-profile/lib"
