[tools]
bun = "latest"
node = "latest"
pnpm = "latest"
uv = "latest"
go = "latest"
java = "latest"

# pi-shazam
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:yaml-language-server" = "latest"

# pi coding agent
"npm:@earendil-works/pi-coding-agent" = "latest"

[settings]
npm.bun = true
idiomatic_version_file_enable_tools = ["python"]
lockfile = true
